language: android
jdk: oraclejdk7

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
#    - android-22
    # - extra

    # The BuildTools version used by your project
#    - build-tools-22.0.1

    # The SDK version used to compile your project
#    - android-22
#    - extra-android-support

    # Additional components
#    - extra-google-google_play_services
#    - extra-google-m2repository
#    - extra-android-m2repository
#    - addon-google_apis-google-22

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

script:
    - cd SnippyAS; ./gradlew foo #./gradlew build assembleTravis crashlyticsUploadDistributionTravis --info


deploy:
  provider: releases
  api_key: $GithubKey
  file: "SnippyAS/app/build/outputs/apk/app-travis.apk"
  skip_cleanup: true
  on:
    tags: false
